# Railway Deployment Configuration
provider = "nixpacks"

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[[services]]
name = "c2-backend"
source = "c2-backend"

[[services]]
name = "c2-frontend" 
source = "c2-frontend"